### ISSUE TITLE
PALAUTE KOODISTA TurnausOhjelma			(Koodi ladattu 11.12.2018 9:45)

### ISSUE THREAD

**Issue by tvierz** [StarSovu/ot-harjoitustyo#1]
##PALAUTE KOODISTA TurnausOhjelma			(Koodi ladattu 11.12.2018 9:45)

En käsittänyt aivan täydellisesti mitä ohjelma tekee, mutta lähdin siitä olettamuksesta, että kyseessä on ohjelma, jonka avulla voidaan pitää kirjaa erilaisista turnauksista, joissa on kaksi joukkuetta jotka voivat saada pisteitä, tämän lisäksi kirjanpitoa voidaan päivittää reaaliaikaisesti.
Ohjelmaa pyöritettyä sen toiminta alkoi selkenemään, sillä sen muotoilu oli tehty hyvin.

####YHTEENVETONA:

Ohjelma on rakennettu hyvin, jolloin sen tulkitseminen ei käy raskaaksi, sen metodit ja jäsentely on tehty hyvin, mutta ohjelma ei osaa käsitellä joitakin käyttäjän antamia syötteitä, jolloin se kaatuu.

Kaatuminen johtaa siihen, että käyttäjä menettää sen yhteydessä kaikki ohjelman tiedot, sillä ohjelma ei tallenna niitä minnekkään. Kaatuminen on kuitenkin todennäköistä jossakin vaihessa, sillä ohjelma ei tarkasta kaikkia syötteitä niiden kelvollisuuden varalta, jolloin kirjoitusvirhe käyttäjän toimesta voi johtaa ison pelin tietojen katoamiseen.

Ohjelmalle voi generoida .jar tiedoston, jolloin sitä voidaan käyttää komentoriviltä, mutta en itse välittömästi tajunnut tätä ja ihmettelin että toimiiko tuo .jar tiedosto ollenkaan.

#####Hyvää:

-Ohjelman idea on hyvä, ja sitä voidaan käyttää monenkaltaisten turnausten seuraamisessa

-Ohjelman testikattavuus on erittäin korkea

-Ohjelman Luokat ovat nimetty hyvin, ja metodit ovat hyvän pituisia, jolloin ohjelmaa on helppo lukea

-Ohjelman jäsentely on tehty luontevasti

-Vaikka en aluksi tajunnut mitä ohjelma tekee, lukemalla koodia ja suorittamalla ohjelmaa, ja katsomalla dokumentaatiota, tämä kuitenkin selvisi suhteellisen hyvin.

#####Paranneltavaa:

-Muutamille metodeille ei ole tehty kaikkia testejä jacoco mukaan esim group -> checkIfDone(){} ei testaa ensimmäisen if{} lausekkeen tulostetta, tälle voidaan tehdä suoraan testi assertTrue(group.checkIfDone()) jos luokan this.done muuttujan arvo on true, tai poistaa/kommentoida väliaikaisesti pois kokonaan, kunnes sitä tarvitaan.

-TeamTest luokka vaikuttaa hieman vajaalta vaikka testikattavuus jacoco:n mukaan on korkea, sillä sen testit eivät vaikuta testaavan muuta kuin joukkueen saamaa nimeä ja goal difference metodia, mutta ei esimerkiksi luokan toiminnallisuutta Game luokan kanssa

-Ohjelmalle voisi luoda yksinkertaisen käyttöliittymän, jonka avulla sitä voisi käyttää omassa ikkunassaan komentorivin ulkopuolella
esimerkiksi luomalla javaFX:llä ikkuna jossa on syötelaatikko(textBox()), tulosteikkuna(Label()), ja syötenappi(Button()).

-Ohjelmalle voisi luoda yksinkertaisen tallennusominaisuuden, jonka avulla vanhat pelit ja turnaukset voitaisiin tallentaa uniikilla nimellä tiedostoksi. Tämä voitaisiin toteuttaa esimerkiksi kirjoittamalla tekstitiedostoon ryhmät ja niiden tulokset. 
esimerkkinä:
Ryhmä 1
tiimi1 - tiimi2 (2-0)
tiimi3 - tiimi4 (1-1)
Ryhmä 2
Tiimi5 -tiimi7 (5-6)

tämän avulla ilmenisi miten jokin vanha turnaus on edennyt.

-Ohjelman koodiin voisi lisätä joihinkin monimutkaisempiin metodeihin, kuten Group luokan metodiin addGameToTeams(int gameNumber, int goals1, int goals2){}, kommentin sen yhteyteen, jolloin ulkopuolisen henkilön on helpompi ymmärtää mitä metodi oikeasti tekee. Ja vaikka metodit itsessään eivät olisikaan monimutkaisia, kun kommentit selittävät mitä eri metodit tekevät, ulkopuolisen koodaajan on helpompi ymmärtää mitä ohjelma tekee ja miten se toimii. Nämä kommentit voivat myös usein olla itse koodin tekijälle myös hyödyllisiä, kun etsitään miksi jokin ohjelman osa ei toimi kuten halutaan.

-Ohjelma ei näytä koskaan lopettavan toimintaansa, ellei se kohtaa virhettä/käyttäjä sammuta komentoikkunaa/paina punaista stop nappia netbeansissa. Lopetusnappi tai komento olisi hyödyllinen käyttäjälle, koska silloin ohjelma on helpointa lopettaa kunnolla.

-Ohjelman .jar tiedoston suoritus ei tee mitään, jolloin sitä pitää käyttää manuaalisesti komentoriviltä.

-Bugeja havaittu

Jos valitaan kahden joukkueen ryhmä ja ryhmiä on 1 kpl, tämän jälkeen ohjelma kysyy missä ryhmässä pelataan(number 0 - 0), jos tälle antaa jonkin muun arvon kuin 0, ohjelma kaatuu.
Havaittavissa syötteellä
2
1
tiimi1
tiimi2
1
-> kaatuu viestillä
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.mycompany.tournament.logic.GroupStage.getGroup(GroupStage.java:23)
	at com.mycompany.tournament.Main.main(Main.java:66)

Ohjelma kaatuu annettaessa tuloksia, jos annettua ryhmän numeroa ei ole olemassa
esim. syöte
2
2
tiimi1
tiimi11
tiimi111
tiimi1111
1
0
4
1
-> (tilanne nyt 4-1)
1
10
5
-> kaatuu viestillä
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 5, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.mycompany.tournament.Main.main(Main.java:104)

Ohjelma kaatuu jos maaleja annettaessa ei annetakkaan kokonaislukua vaan esimerkiksi double, tai String arvo esim syöte:
How many teams in a group?
2

How many groups?
1

Group 0
Name of team 1: 0
Name of team 2: 4

In which group do you want to play? (Number 0 - 0)
1.5
-> kaatuu viestillä
Exception in thread "main" java.lang.NumberFormatException: For input string: "1.5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.mycompany.tournament.Main.main(Main.java:58)

**Comment by teepiik** [comment]
Erittäin hyvä palaute, josta on varmista apua myös palautteen saajalle!
